version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.16
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y maven
      - run:
          name: Build and Compile
          command: mvn clean install

workflows:
  version: 2
  build_and_compile:
    jobs:
      - build